/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Quiz2;
import Quiz2.Tambah;
import Quiz2.Koneksi;
import java.sql.*;
import java.awt.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/**
 *
 * @author Azis Nurjaman
 */
public class home extends javax.swing.JFrame {
    DefaultTableModel tabModel;
    ResultSet RsKaryawan;
    
    private void tampilData(String where){
        try{
            Object[] judul = {"ID", "First Name", "Last Name", "Age"};
            tabModel = new DefaultTableModel(null, judul);
            TabKaryawan.setModel(tabModel);
            
            Connection con = (Connection) Koneksi.konek();
            Statement st = con.createStatement();
            tabModel.getDataVector().removeAllElements();
            
            RsKaryawan = st.executeQuery("select * from info" + where);
            while (RsKaryawan.next()){
                Object[] data = {
                  RsKaryawan.getString("id"),
                  RsKaryawan.getString("fname"),
                  RsKaryawan.getString("lname"),
                  RsKaryawan.getString("age"),
                };
                tabModel.addRow(data);
            }
        } catch (Exception e){
            System.err.println(e.getMessage());   
        }
    }
    /**
     * Creates new form Quiz2
     */
    public home() {
        setTitle("Home");
        initComponents();
    }
    String id = "";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabKaryawan = new javax.swing.JTable();
        View = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Karyawan");

        TabKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Age"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabKaryawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabKaryawan);

        View.setText("View");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(View)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Add)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(View)
                    .addComponent(Delete)
                    .addComponent(Add)
                    .addComponent(Update))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        Tambah Add = new Tambah();
        Add.setVisible(true);
        dispose();
    }//GEN-LAST:event_AddActionPerformed

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        // TODO add your handling code here:
        tampilData("");
    }//GEN-LAST:event_ViewActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        try {
            int jawab;
            if (TabKaryawan.getSelectedRow() < 0) {
                    JOptionPane.showMessageDialog(null, "Select data first");
            } else {
                if ((jawab = JOptionPane.showConfirmDialog(null, "Are you sure want to delete this data?", "Attention", JOptionPane.YES_NO_OPTION)) == 0) {
                    
                    Connection con = (Connection) Koneksi.konek();
                    Statement st = con.createStatement();
                    st = con.createStatement();
                    st.executeUpdate("DELETE FROM info WHERE id='"
                    + tabModel.getValueAt(TabKaryawan.getSelectedRow(), 0) + "'");
                    tampilData("");
                    JOptionPane.showMessageDialog(null, "Data has been deleted");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        try {
            if (id == null || id.equals("")) {
                    JOptionPane.showMessageDialog(null, "Select data first");
            } else {
                Update update = new Update();
                update.setVisible(true);
                update.fillUpdate(id);
                dispose();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        /*+try {
            int jawab, answere;
            if (TabKaryawan.getSelectedRow() < 0) {
                    JOptionPane.showMessageDialog(null, "Select data first");
            } else {
                if ((jawab = JOptionPane.showConfirmDialog(null, "Are you sure want to update this data?", "Attention", JOptionPane.YES_NO_OPTION)) == 0) {
                    
                    Connection con = (Connection) Koneksi.konek();
                    Statement st = con.createStatement();
                    st = con.createStatement();
                    PreparedStatement stmt = con.prepareStatement("UPDATE FROM info SET"
                    + "fname = '" + tabModel.getValueAt(TabKaryawan.getSelectedRow(), 1) + "', "
                    + "lname = '" + tabModel.getValueAt(TabKaryawan.getSelectedRow(), 2) + "', "
                    + "age = '" + tabModel.getValueAt(TabKaryawan.getSelectedRow(), 3) + "' ");
                    stmt.executeUpdate();
                    tampilData("");
                    JOptionPane.showMessageDialog(null, "Data has been updated");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }*/
    }//GEN-LAST:event_UpdateActionPerformed

    private void TabKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabKaryawanMouseClicked
        // TODO add your handling code here:
        boolean a = TabKaryawan.isEditing();
        if(a == false){
            int jawab;
            if ((jawab = JOptionPane.showConfirmDialog(null, "Are you sure you want to select this data?", "Attention", JOptionPane.YES_NO_OPTION)) == 0) {
                DefaultTableModel dtm = (DefaultTableModel) TabKaryawan.getModel();
                int selectRowIndex = TabKaryawan.getSelectedRow();
                id = (String) dtm.getValueAt(selectRowIndex, 0);
                System.out.println(id);
            }
        }
    }//GEN-LAST:event_TabKaryawanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Delete;
    private javax.swing.JTable TabKaryawan;
    private javax.swing.JButton Update;
    private javax.swing.JButton View;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
